project:
  type: website

website:
  title: "pankid"
  bread-crumbs: true
  back-to-top-navigation: true
  page-footer: "“我们在日常生活中度过的每一天，实际上也许是连续发生的奇迹也说不定呢。”"
  reader-mode: true

  navbar:
    background: primary
    foreground: light
    pinned: true
    search: true
    left:
      - text: "个人简历"
        file: about.qmd
      - text: "我的博客"
        file: blog.qmd
      - text: "推荐资料"
        file: reference.qmd
      - text: "图片记录"
        file: image.qmd
      - text: "视频记录"
        file: video.qmd
    right:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
      - icon: google
        href: https://www.google.com

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



